theme: jekyll-theme-primer

title: Sara Rands, Therapist
description: Therapy for deep thinkers, gifted adults, and highly sensitive people.

markdown: kramdown
permalink: /blog/:title/
baseurl: "/sararands-site"
kramdown:
  input: GFM